### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by pafnuty** [dle-modules/Related-Link#2]
@punpun1 
Предлагаю соблюдать принятые стандарты написания кода и не смотреть на то, как принято писать в исходниках DLE.

**Comment by lazyphpdev** [comment]
@pafnuty к примеру?

**Comment by pafnuty** [comment]
Ну самый простой способ - открыть файл в phpstorm и автоматически
отформатировать )
Попробую вечерком это сделать, заодно может идеи по улучшению появятся.

25 июн 2017 г. 5:40 AM пользователь "Vova" <notifications@github.com>
написал:

**Comment by lazyphpdev** [comment]
@pafnuty у меня есть одна идея, я создам новый issues для этого, и нужна помощь в этом.

**Comment by pafnuty** [comment]
http://www.php-fig.org/psr/

http://www.php-fig.org/psr/psr-2/

**Comment by lazyphpdev** [comment]
@pafnuty окей, принял к сведению. Отформатирую его по полной. ;)
