### ISSUE TITLE
Кольцевая для мультикатегорий

### ISSUE THREAD

**Issue by lazyphpdev** [dle-modules/Related-Link#3]
Вот в чем проблема, не могу понять как сделать кольцевую для мультикатегорий. Суть вот в чем:
При заходе в новость у которой $category_id = 1, будут выводиться новости с такой категорией, но, при заходе в новость с этого списка у новости $category_id может быть 2.

**Comment by pafnuty** [comment]
@punpun1 тут, боюсь, ничего не поделать, будет не кольцевая уже, но текоретически кольцо может и замкнётся когда-нибудь.

**Comment by lazyphpdev** [comment]
@pafnuty я уже нашел как это решить
